---
title: "p8105_hw2_yz5248"
author: "yz5248"
date: "2025-09-24"
output: github_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(readxl)
```

Problem 1. 
First, clean the data in pols-month.csv.  
Breaking up the variable mon into integer variables year, month, and day.  
Replacing month number with month name.  
Creating a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.
```{r}
pols_clean = read_csv("fivethirtyeight_datasets/pols-month.csv")|>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.name[month],
    president = if_else(prez_gop == 1, "gop", "dem")
  ) |>
  select(-prez_gop, -prez_dem, -day)



```


```{r}

snp_clean = read_csv("fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(
    # 把 year 转成 4 位数
    year = as.integer(if_else(as.integer(year) > 50, paste0("19", year), paste0("20", year))),
    month = as.integer(month),
    month = month.name[month]
  ) |>
  select(year, month, close) |>
  arrange(year, match(month, month.name))

```

```{r}
unemp_clean = unemp <- read_csv("fivethirtyeight_datasets/unemployment.csv")|>
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(month = recode(month,
                        Jan="January", Feb="February", Mar="March",
                        Apr="April", May="May", Jun="June",
                        Jul="July", Aug="August", Sep="September",
                        Oct="October", Nov="November", Dec="December")) |>
  rename(year = Year)


```

```{r}
merged_data = pols_clean |>
  left_join(snp_clean, by = c("year", "month")) |>
  left_join(unemp_clean, by = c("year", "month"))

tibble(
  Rows = nrow(merged_data),
  Columns = ncol(merged_data),
  Year_Min = min(merged_data$year, na.rm = TRUE),
  Year_Max = max(merged_data$year, na.rm = TRUE)
)

```


Problem 2. 

```{r}
mr_trash_wheel = read_excel(
  "202409 Trash Wheel Collection Data.xlsx",sheet = "Mr. Trash Wheel", skip = 1) |>
  janitor::clean_names() |>       # make column names snake_case
  filter(!is.na(dumpster)) |>     # keep only rows with data
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

```

